version: '3.8'
services:
  userservice:
    build:
      context: .
      dockerfile: ./FN.UserService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  emailservice:
    build:
      context: .
      dockerfile: ./FN.EmailService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  orderservice:
    build:
      context: .
      dockerfile: ./FN.OrderService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  catalogservice:
    build:
      context: .
      dockerfile: ./FN.CatalogService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  apigateway:
    build:
      context: .
      dockerfile: ./FN.APIGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - USERSERVICE_URL=http://userservice:80
      - ORDERSERVICE_URL=http://orderservice:80
      - CATALOGSERVICE_URL=http://catalogservice:80
      - EMAILSERVICE_URL=http://emailservice:80
